### PR TITLE
Fix bugs related to tail bit puncturing

### PR DESCRIPTION
**Pull request by rear1019**

### CODE REVIEW

**Comment by fwunsch** [comment]
Can't really test right now, could you describe the bug you were having or how you discovered the bug?

**Comment by rafael2k** [comment]
I'm also interested to know why is this fix needed.

**Comment by rear1019** [comment]
I have already replied to Felix in a private message, with hindsight I should have posted it here.

**Fix bug in tail bit puncturing**
The number of bits on level `p` assuming Equal Error Protection is calculated by `M_p = RX_p * floor((2*N_2 - 12) / RY_p))` (chapter 7.3.1.1 in DRM System Specification [ETSI ES 201 980]). The number of coded bits including tailbits is `(M_p + 6) * 6`. This value is called `d_vlen_in` in [punct_bb_impl.cc](https://github.com/kit-cel/gr-drm/blob/bf575c7b9751b4a5948816223eed5138cc995ad1/lib/punct_bb_impl.cc). `d_vlen_in` is not always a multiple of 36. This is why the very first index used to access the puncturing pattern for the tailbits is not always 0 (lines 81 and 97 in [punct_bb_impl.cc](https://github.com/kit-cel/gr-drm/blob/bf575c7b9751b4a5948816223eed5138cc995ad1/lib/punct_bb_impl.cc)). However, the first index must be 0 if I interpret chapter 7.3.2 of DRM System Specification correctly.

For example assume Spectrum Occupancy 10 kHz, Robustness Mode B and 64-QAM Standard Mapping for MSC with Protection Level 3 on level `p = 2` => `N_2 = 2337` (Table 42 in DRM System Specification), `RX_p = 8` and `RY_p = 9` (Table 32 in DRM System Specification) => `M_p = 4144` => `d_vlen_in = 24900`. The first index used to access the puncturing pattern for the tailbits is `24864 % 36 = 24`, see lines 81 and 97 in [punct_bb_impl.cc](https://github.com/kit-cel/gr-drm/blob/bf575c7b9751b4a5948816223eed5138cc995ad1/lib/punct_bb_impl.cc). Note: `d_n_tail` is always 36 and `len_pp2` for MSC and SDC is always 36 (chapter 7.3.2/Table 28 in DRM System Specification). No special handling for FAC is required as the numbers work out correctly.

**Fix tail bit puncturing pattern for SDC with 4-QAM**
As mentioned above, the length of the puncturing pattern for the tailbits is always 36 in case of MLC and SDC. I discovered this is not true for SDC with 4-QAM. This is possibly a copy-&-paste error. The code for FAC (always 4-QAM) is almost equal to the one for SDC with 4-QAM, see lines 12–23 and 45–56 in [mlc_factory.py](https://github.com/kit-cel/gr-drm/blob/bf575c7b9751b4a5948816223eed5138cc995ad1/python/mlc_factory.py). However, special handling of tailbits is always required in case of MSC and SDC (chapter 7.3.2 DRM System Specification).

**Comment by rafael2k** [comment]
Thanks for the explanation!

**Comment by fwunsch** [comment]
Thank you for your contribution and sorry for not merging this earlier!

**Pull request merged**
